apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-sleep
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: postgres-client
        image: christianwoehrle/postgres-validator
        imagePullPolicy: Always
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres.${POSTGRES_DB_NAME}.credentials
        - name: URL_MASTER
          value: ${POSTGRES_DB_NAME}
        - name: URL_REPLICA
          value: ${POSTGRES_DB_NAME}-repl
        - name: USERNAME
          value: postgres
        command: ["sleep", "3600"]
        securityContext:
          runAsUser: 1000
      restartPolicy: Never

